name: build

on:
  push:
    branches:
      - main
jobs:
  build-main:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: abell.registry.macslabs.de/docker
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0 # all history for all branches and tags
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print tolower($2)}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=${GITHUB_REF_NAME#v} >> $GITHUB_OUTPUT
          echo SHA_SHORT=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: abell.registry.macslabs.de
          username: ${{ secrets.DR_ABELL_USER }}
          password: ${{ secrets.DR_ABELL_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: |
            linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.SHA_SHORT }}