name: update

on:
  push:
    branches:
      - dev
jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_ORG: hotbird.docker.nexus.macslabs.de/docker
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # all history for all branches and tags
      - name: Update Phanpy
        id: update
        run: |
          curr=$(cat Dockerfile | grep PHANPY_VERSION | head -n1 | awk -F'=' '{print $2}' | tr -d '"')
          latest=$(curl --silent "https://api.github.com/repos/cheeaun/phanpy/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
          if [ "$curr" != "$latest" ]; then
            echo "There is a new latest release: $latest , updating from $curr"
            echo "CREATE_PR=true" >> $GITHUB_ENV
            sed -i -e 's/'$curr'/'$latest'/g' Dockerfile
          fi
      - name: Commit Back
        if: ${{ env.CREATE_PR != '' }}
        id: commit
        run: |
          # add to git and commit
          git config user.email service.updater@home.lab
          git config user.name Service Updater
          git add Chart.yaml
          if git status --porcelain | grep .; then
              git commit -am 'updated dependency'
              git push || true
              echo Repo is updated
              echo "CREATE_PR=true" >> $GITHUB_ENV
          else
              echo Repo is clean
          fi
      - name: Create PR
        if: ${{ env.CREATE_PR != '' }}
        uses: deb4sh/tea-pr@main
        with:
          token: ${{ secrets.AUTOMATIC_PR_TOKEN }}
          base: 'main'
